
AWSTemplateFormatVersion: 2010-09-09
Description: Desplega servidor para curso de Lima.
Mappings:
  RegionMap:
    us-east-1:
      UbuntuAmi: "ami-0ac019f4fcb7cb7e6" #Ubuntu 18.04
      RegionAlias: "Virginia"

Resources:
    Ec2InstanceAirflow:
        Type: AWS::EC2::Instance
        DeletionPolicy: Delete
        Properties:
            InstanceInitiatedShutdownBehavior: terminate
            SubnetId: subnet-429c8d6d
            InstanceType: "t2.micro"
            ImageId: !FindInMap [ RegionMap, !Ref "AWS::Region" , UbuntuAmi ]
            SecurityGroupIds:
                - "sg-0c1b5430204e8ccd3"
            KeyName: "sg-0c1b5430204e8ccd3"
            Tags:
            - Key: Name
              Value: !Sub "Curso-Peru-Hola-Mama"
            UserData:
                Fn::Base64: !Sub |
                    #!/bin/bash
                    echo " ####################  apt install"
                    apt-get update -y
                    apt install awscli -y