
AWSTemplateFormatVersion: 2010-09-09
Description: Desplega servidor para curso de Lima.
Mappings:
  RegionMap:
    us-east-1:
      UbuntuAmi: "ami-0ac019f4fcb7cb7e6" #Ubuntu 18.04
      RegionAlias: "Virginia"

Resources:
    Ec2InstanceAirflow:
        Type: AWS::EC2::Instance
        DeletionPolicy: Delete
        Properties:
            InstanceInitiatedShutdownBehavior: terminate
            SubnetId: subnet-1d8be041 # se extrae de la vpc
            InstanceType: "t2.micro"
            ImageId: !FindInMap [ RegionMap, !Ref "AWS::Region" , UbuntuAmi ]
            SecurityGroupIds:
                - "sg-73410c37" #grupo de seguridad de ma misma vps
            KeyName: "curso-lima"
            Tags:
            - Key: Name
              Value: !Sub "Curso-Peru-Hola-Mama"
            UserData:
                Fn::Base64: !Sub |
                    #!/bin/bash
                    echo " ####################  apt install"
                    apt-get update -y
                    apt install awscli -y
